#!/usr/bin/env python3
"""
MemPalace memory provider for Hermes.

Implements the Hermes MemoryProvider ABC, plugging MemPalace in as a
first-class memory backend. Every conversation turn is filed into the palace
automatically — wing-classified, semantic-search ready, permanent.

Configuration (all optional):
  ~/.mempalace/identity.txt     — Layer 0 identity block (loaded every session)
  ~/.mempalace/wing_config.json — Wing routing rules (generated by mempalace init)

Run `mempalace init <your-project-dir>` to generate these files.
"""

from __future__ import annotations

import json
import logging
import queue
import threading
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("mempalace.hermes")


# ---------------------------------------------------------------------------
# Provider class
# ---------------------------------------------------------------------------


class MempalaceProvider:
    """
    Hermes MemoryProvider implementation backed by MemPalace.

    Wing config and identity are loaded from ~/.mempalace/ at initialize()
    time — no hardcoded personal data anywhere in this file.
    """

    PROVIDER_NAME = "mempalace"

    # ------------------------------------------------------------------ init

    def __init__(self):
        self._config: dict = {}
        self._palace_path: str = ""
        self._wing_config: dict = {}
        self._identity: str = ""
        self._wake_up_cache: str = ""
        self._worker_queue: queue.Queue = queue.Queue()
        self._worker_thread: threading.Thread | None = None
        self._initialized = False
        # ChromaDB client cached here so all callers share one connection
        self._chroma_client = None
        self._chroma_collection = None
        self._chroma_lock = threading.Lock()

    # --------------------------------------------------------- provider hooks

    @classmethod
    def get_config_schema(cls) -> list[dict]:
        return [
            {
                "key": "palace_path",
                "description": "Path to palace directory (default: ~/.mempalace/palace)",
                "required": False,
                "default": "~/.mempalace/palace",
            },
            {
                "key": "identity_path",
                "description": (
                    "Path to identity.txt (L0 layer, loaded every session). "
                    "Create with `mempalace init`."
                ),
                "required": False,
                "default": "~/.mempalace/identity.txt",
            },
            {
                "key": "wing",
                "description": "Default wing for filing (default: auto-classify via wing_config.json)",
                "required": False,
                "default": "",
            },
            {
                "key": "n_prefetch",
                "description": "Number of semantic search results to inject before each turn",
                "required": False,
                "default": 3,
            },
        ]

    def initialize(self, config: dict) -> None:
        """Load config, wing routing, identity, warm up wake-up cache, start worker."""
        self._config = config or {}

        palace_path = self._config.get("palace_path", "~/.mempalace/palace")
        self._palace_path = str(Path(palace_path).expanduser())

        # Load wing config if present — do not create it
        wing_config_path = Path(self._palace_path).parent / "wing_config.json"
        if wing_config_path.exists():
            try:
                with open(wing_config_path) as f:
                    self._wing_config = json.load(f).get("wings", {})
                logger.info("MemPalace: loaded wing config from %s", wing_config_path)
            except Exception as exc:
                logger.warning("MemPalace: could not load wing_config.json: %s", exc)
                self._wing_config = {}
        else:
            self._wing_config = {}
            logger.info(
                "MemPalace: no wing_config.json found — run `mempalace init` to configure wings"
            )

        # Load identity if present
        identity_path = Path(
            self._config.get("identity_path", "~/.mempalace/identity.txt")
        ).expanduser()
        self._identity = (
            identity_path.read_text(encoding="utf-8").strip()
            if identity_path.exists()
            else ""
        )

        # Create ChromaDB client once so all callers share a single connection
        import chromadb as _chromadb

        self._chroma_client = _chromadb.PersistentClient(path=self._palace_path)
        self._chroma_collection = self._chroma_client.get_or_create_collection(
            "mempalace_drawers"
        )
        logger.info("MemPalace: ChromaDB client ready (palace=%s)", self._palace_path)

        # Start background filing worker
        self._worker_thread = threading.Thread(
            target=self._background_worker, daemon=True, name="mempalace-worker"
        )
        self._worker_thread.start()

        self._initialized = True
        logger.info("MemPalace: initialized (palace=%s)", self._palace_path)

        # Warm up wake-up cache in background — avoids blocking initialize()
        threading.Thread(
            target=self._refresh_wake_up_cache, daemon=True, name="mempalace-wakeup"
        ).start()

    def system_prompt_block(self) -> str:
        """Inject identity + AAAK wake-up at session start."""
        if not self._wake_up_cache:
            return ""
        block = "# MemPalace Context\n"
        if self._identity:
            block += self._identity + "\n\n"
        block += self._wake_up_cache
        return block

    def prefetch(self, query: str) -> str:
        """Semantic search before each turn; results injected as context."""
        if not query or not self._palace_path:
            return ""
        try:
            from mempalace.searcher import search_memories

            n = int(self._config.get("n_prefetch", 3))
            results = search_memories(query, palace_path=self._palace_path, n_results=n)
            if not results:
                return ""
            lines = ["## MemPalace — relevant context"]
            for r in results:
                wing = r.get("wing", "")
                room = r.get("room", "")
                tag = f"[{wing}/{room}] " if wing else ""
                lines.append(f"{tag}{r.get('document', '').strip()}")
            return "\n\n".join(lines)
        except Exception as exc:
            logger.debug("MemPalace prefetch error: %s", exc)
            return ""

    def sync_turn(self, turn: dict) -> None:
        """File an exchange to the palace (non-blocking — queued to background thread)."""
        if turn:
            self._worker_queue.put(("file_turn", turn))

    def on_session_end(self, session: dict) -> None:
        """Mine the full session and regenerate AAAK critical-facts layer."""
        self._worker_queue.put(("session_end", session))
        # Refresh wake-up cache for next session (background — non-blocking)
        threading.Thread(
            target=self._refresh_wake_up_cache, daemon=True, name="mempalace-wakeup"
        ).start()

    def on_pre_compress(self, messages: list[dict]) -> list[dict]:
        """Extract key exchanges before Hermes compresses context."""
        try:
            self._worker_queue.put(("pre_compress", messages))
        except Exception as exc:
            logger.debug("MemPalace pre-compress error: %s", exc)
        return messages

    # --------------------------------------------------------------- tools

    def get_tools(self) -> list[dict]:
        """8 tools exposed to the Hermes agent."""
        return [
            {
                "name": "mempalace_search",
                "description": "Semantic search across all palace sessions.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "Search query"},
                        "wing": {"type": "string", "description": "Limit to one wing"},
                        "room": {"type": "string", "description": "Limit to one room"},
                        "n_results": {
                            "type": "integer",
                            "description": "Number of results (default: 5)",
                            "default": 5,
                        },
                    },
                    "required": ["query"],
                },
                "handler": self._tool_search,
            },
            {
                "name": "mempalace_status",
                "description": "Palace overview: total drawers, wing/room breakdown, AAAK spec.",
                "parameters": {"type": "object", "properties": {}},
                "handler": self._tool_status,
            },
            {
                "name": "mempalace_list_wings",
                "description": "List all wings with drawer counts.",
                "parameters": {"type": "object", "properties": {}},
                "handler": self._tool_list_wings,
            },
            {
                "name": "mempalace_list_rooms",
                "description": "List rooms within a wing.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "wing": {"type": "string", "description": "Wing name"}
                    },
                    "required": ["wing"],
                },
                "handler": self._tool_list_rooms,
            },
            {
                "name": "mempalace_kg_query",
                "description": "Query entity relationships in the knowledge graph, with optional time filtering.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "entity": {"type": "string", "description": "Entity name"},
                        "since": {
                            "type": "string",
                            "description": "ISO date lower bound (optional)",
                        },
                    },
                    "required": ["entity"],
                },
                "handler": self._tool_kg_query,
            },
            {
                "name": "mempalace_kg_add",
                "description": "Add a fact to the knowledge graph.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "subject": {"type": "string"},
                        "predicate": {"type": "string"},
                        "object": {"type": "string"},
                    },
                    "required": ["subject", "predicate", "object"],
                },
                "handler": self._tool_kg_add,
            },
            {
                "name": "mempalace_diary_write",
                "description": "Write an AAAK diary entry.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "entry": {"type": "string", "description": "Diary entry text"}
                    },
                    "required": ["entry"],
                },
                "handler": self._tool_diary_write,
            },
            {
                "name": "mempalace_diary_read",
                "description": "Read recent diary entries.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "n": {
                            "type": "integer",
                            "description": "Number of entries to return (default: 10)",
                            "default": 10,
                        }
                    },
                },
                "handler": self._tool_diary_read,
            },
        ]

    # ---------------------------------------------------------- tool handlers

    def _tool_search(self, query: str, wing: str = None, room: str = None, n_results: int = 5) -> dict:
        try:
            from mempalace.searcher import search_memories

            results = search_memories(
                query,
                palace_path=self._palace_path,
                wing=wing,
                room=room,
                n_results=n_results,
            )
            return {"results": results, "count": len(results)}
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_status(self) -> dict:
        try:
            col = self._get_collection()
            if col is None:
                return {"error": "MemPalace not initialized"}
            count = col.count()
            metas = col.get(include=["metadatas"])["metadatas"]
            wings: dict[str, int] = {}
            for m in metas:
                w = m.get("wing", "unknown")
                wings[w] = wings.get(w, 0) + 1
            return {
                "total_drawers": count,
                "wings": wings,
                "palace_path": self._palace_path,
            }
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_list_wings(self) -> dict:
        try:
            col = self._get_collection()
            if col is None:
                return {"error": "MemPalace not initialized"}
            metas = col.get(include=["metadatas"])["metadatas"]
            wings: dict[str, int] = {}
            for m in metas:
                w = m.get("wing", "unknown")
                wings[w] = wings.get(w, 0) + 1
            return {"wings": wings}
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_list_rooms(self, wing: str) -> dict:
        try:
            col = self._get_collection()
            if col is None:
                return {"error": "MemPalace not initialized"}
            metas = col.get(where={"wing": wing}, include=["metadatas"])["metadatas"]
            rooms: dict[str, int] = {}
            for m in metas:
                r = m.get("room", "unknown")
                rooms[r] = rooms.get(r, 0) + 1
            return {"wing": wing, "rooms": rooms}
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_kg_query(self, entity: str, since: str = None) -> dict:
        try:
            from mempalace.knowledge_graph import KnowledgeGraph

            kg = KnowledgeGraph(palace_path=self._palace_path)
            results = kg.query(entity, since=since)
            return {"entity": entity, "relations": results}
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_kg_add(self, subject: str, predicate: str, object: str) -> dict:
        try:
            from mempalace.knowledge_graph import KnowledgeGraph

            kg = KnowledgeGraph(palace_path=self._palace_path)
            kg.add(subject=subject, predicate=predicate, object=object)
            return {"status": "ok", "triple": [subject, predicate, object]}
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_diary_write(self, entry: str) -> dict:
        try:
            diary_path = Path(self._palace_path).parent / "diary.jsonl"
            record = {
                "ts": datetime.utcnow().isoformat(),
                "entry": entry,
            }
            with open(diary_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(record) + "\n")
            return {"status": "ok"}
        except Exception as exc:
            return {"error": str(exc)}

    def _tool_diary_read(self, n: int = 10) -> dict:
        try:
            diary_path = Path(self._palace_path).parent / "diary.jsonl"
            if not diary_path.exists():
                return {"entries": []}
            lines = diary_path.read_text(encoding="utf-8").strip().splitlines()
            recent = [json.loads(line) for line in lines[-n:]]
            return {"entries": recent}
        except Exception as exc:
            return {"error": str(exc)}

    # -------------------------------------------------------- internal helpers

    def _get_collection(self):
        """Return the cached ChromaDB collection, or None if not yet initialized."""
        with self._chroma_lock:
            return self._chroma_collection

    def _refresh_wake_up_cache(self) -> None:
        """Regenerate AAAK wake-up context and store in cache (safe to run in thread)."""
        try:
            self._wake_up_cache = self._generate_wake_up()
        except Exception as exc:
            logger.debug("MemPalace wake-up refresh error: %s", exc)

    def _generate_wake_up(self) -> str:
        """Generate AAAK wake-up context from the palace (L1 layer)."""
        try:
            from mempalace.layers import MemoryStack

            stack = MemoryStack(palace_path=self._palace_path)
            wing = self._config.get("wing") or None
            return stack.wake_up(wing=wing)
        except Exception as exc:
            logger.debug("MemPalace wake-up generation error: %s", exc)
            return ""

    def _classify_wing(self, text: str) -> str:
        """
        Route content to a wing based on loaded wing_config keywords.
        Returns 'wing_general' when no wing_config is loaded or no keyword matches.
        """
        if not self._wing_config:
            return "wing_general"

        text_lower = text.lower()
        for wing_name, wing_def in self._wing_config.items():
            keywords = wing_def.get("keywords", [])
            if any(kw.lower() in text_lower for kw in keywords):
                return wing_name

        return "wing_general"

    def _file_turn(self, turn: dict) -> None:
        """Write a single turn exchange to the palace."""
        try:
            import hashlib

            user_msg = turn.get("user", "")
            assistant_msg = turn.get("assistant", "")
            if not user_msg and not assistant_msg:
                return

            col = self._get_collection()
            if col is None:
                return

            text = f"User: {user_msg}\n\nAssistant: {assistant_msg}".strip()
            wing = self._classify_wing(text)
            room = "conversations"
            ts = datetime.utcnow().isoformat()
            doc_id = hashlib.sha256(f"{ts}:{text[:120]}".encode()).hexdigest()[:16]

            col.upsert(
                ids=[doc_id],
                documents=[text],
                metadatas=[
                    {
                        "wing": wing,
                        "room": room,
                        "source": "hermes",
                        "ts": ts,
                    }
                ],
            )
        except Exception as exc:
            logger.debug("MemPalace _file_turn error: %s", exc)

    def _mine_session(self, session: dict) -> None:
        """Mine a full session dict into the palace at session end."""
        try:
            messages = session.get("messages", [])
            for msg in messages:
                role = msg.get("role", "")
                content = msg.get("content", "")
                if role == "user" and content:
                    # Pair with the next assistant message if available
                    idx = messages.index(msg)
                    assistant_content = ""
                    if idx + 1 < len(messages) and messages[idx + 1].get("role") == "assistant":
                        assistant_content = messages[idx + 1].get("content", "")
                    self._file_turn({"user": content, "assistant": assistant_content})
        except Exception as exc:
            logger.debug("MemPalace _mine_session error: %s", exc)

    def _background_worker(self) -> None:
        """Process filing tasks from the queue in a background thread."""
        while True:
            try:
                task, payload = self._worker_queue.get(timeout=5)
                if task == "file_turn":
                    self._file_turn(payload)
                elif task == "session_end":
                    self._mine_session(payload)
                elif task == "pre_compress":
                    # File key exchanges before compression
                    for msg in payload or []:
                        if msg.get("role") == "user":
                            self._file_turn(
                                {
                                    "user": msg.get("content", ""),
                                    "assistant": "",
                                }
                            )
                self._worker_queue.task_done()
            except queue.Empty:
                continue
            except Exception as exc:
                logger.debug("MemPalace worker error: %s", exc)
